apiVersion: v1
kind: Pod
metadata:
  generateName: custom-backprop-
spec:
  containers:
  - args:
    - profile
    - -w
    - "true"
    - -t 
    - nvtx
    - -s
    - none 
    - -o 
    - /mnt/ceph_rbd/nsight_report_TRuE
    - -f
    - "true"
    - -x 
    - "true"
    - torchrun
    - --nproc_per_node=4
    - chrimera_main.py
    command:
    - nsys
    image: bigballoon8/custom-backprop
    name: custom-backprop
    env:
    - name: OMP_NUM_THREADS
      value: "4"
    resources:
      limits:
        cpu: 16
        memory: 32Gi
        nvidia.com/gpu: 4
      requests:
        cpu: 16
        memory: 16Gi
    volumeMounts:
    - mountPath: /mnt/ceph_rbd
      name: volume
    - mountPath: /dev/shm
      name: devshm
    workingDir: /workspace/experiment3(pipeline_parallelism)/
  nodeSelector:
    nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
  restartPolicy: Never
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: imagenet-pv
  - emptyDir:
      medium: Memory
    name: devshm
